apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 31006
  type: NodePort    