apiVersion: v1
kind: Service
metadata:
  name: multithread-service
spec:
  selector:
    app: multithread-react
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 31006
  type: NodePort    